-- MySQL Script generated by MySQL Workbench
-- Mon Aug 15 20:38:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(320) NOT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idNurses_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Nurse_Email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 63
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`fitbitdatabackup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fitbitdatabackup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nurses_ID` INT NOT NULL,
  `dateCreated` DATETIME NOT NULL,
  `activityData` JSON NULL DEFAULT NULL,
  `metric` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_fitbitData_nurses1_idx` (`nurses_ID` ASC) VISIBLE,
  CONSTRAINT `fk_fitbitData_nurses2`
    FOREIGN KEY (`nurses_ID`)
    REFERENCES `mydb`.`user` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`survey_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`survey_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `surveyType` VARCHAR(45) NULL DEFAULT NULL,
  `descrption` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`survey` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(100) NOT NULL,
  `surveyDate` DATE NULL DEFAULT NULL,
  `nurses_ID` INT NULL DEFAULT NULL,
  `survey_type_id` INT NULL DEFAULT NULL,
  `fitbitData_id` INT NULL DEFAULT NULL,
  `dateCompleted` DATETIME NULL DEFAULT NULL,
  `dateStarted` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Survey_survey_type1_idx` (`survey_type_id` ASC) VISIBLE,
  INDEX `fk_Survey_nurses1_idx` (`nurses_ID` ASC) VISIBLE,
  INDEX `fk_Survey_fitbitData1_idx` (`fitbitData_id` ASC) VISIBLE,
  CONSTRAINT `fk_Survey_fitbitData1`
    FOREIGN KEY (`fitbitData_id`)
    REFERENCES `mydb`.`fitbitdatabackup` (`id`),
  CONSTRAINT `fk_Survey_nurses1`
    FOREIGN KEY (`nurses_ID`)
    REFERENCES `mydb`.`user` (`ID`),
  CONSTRAINT `fk_Survey_survey_type1`
    FOREIGN KEY (`survey_type_id`)
    REFERENCES `mydb`.`survey_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 184
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`fitbitdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fitbitdata` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nurses_ID` INT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `step_activity_all` LONGTEXT NULL DEFAULT NULL,
  `step_activity_shift` LONGTEXT NULL DEFAULT NULL,
  `step_activity_preshift` LONGTEXT NULL DEFAULT NULL,
  `step_activity_postshift` LONGTEXT NULL DEFAULT NULL,
  `hr_activity_all` LONGTEXT NULL DEFAULT NULL,
  `hr_activity_shift` LONGTEXT NULL DEFAULT NULL,
  `hr_activity_preshift` LONGTEXT NULL DEFAULT NULL,
  `hr_activity_postshift` LONGTEXT NULL DEFAULT NULL,
  `sleep` LONGTEXT NULL DEFAULT NULL,
  `survey_ID` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_fitbitData_nurses1_idx` (`nurses_ID` ASC) VISIBLE,
  INDEX `fk_fitbitData_survey1_idx` (`survey_ID` ASC) VISIBLE,
  CONSTRAINT `fk_fitbitData_nurses1`
    FOREIGN KEY (`nurses_ID`)
    REFERENCES `mydb`.`user` (`ID`),
  CONSTRAINT `fk_fitbitData_survey1`
    FOREIGN KEY (`survey_ID`)
    REFERENCES `mydb`.`survey` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 122
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`offered_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`offered_answer` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `AnswerText` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questionText` VARCHAR(200) NULL DEFAULT NULL,
  `survey_type_id` INT NULL DEFAULT NULL,
  `daily_survey_type` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_question_survey_type1_idx` (`survey_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_survey_type1`
    FOREIGN KEY (`survey_type_id`)
    REFERENCES `mydb`.`survey_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`question_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question_answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Question_Id` INT NULL DEFAULT NULL,
  `OfferedAnswer_Id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `sqa_question_id_fk_idx` (`Question_Id` ASC) VISIBLE,
  INDEX `offered_answer_id_fk_idx` (`OfferedAnswer_Id` ASC) VISIBLE,
  CONSTRAINT `offered_answer_id_fk`
    FOREIGN KEY (`OfferedAnswer_Id`)
    REFERENCES `mydb`.`offered_answer` (`Id`),
  CONSTRAINT `sqa_question_id_fk`
    FOREIGN KEY (`Question_Id`)
    REFERENCES `mydb`.`question` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`shiftdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shiftdata` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `startTime` MEDIUMTEXT NULL DEFAULT NULL,
  `endTime` MEDIUMTEXT NULL DEFAULT NULL,
  `survey_Id` INT NOT NULL,
  PRIMARY KEY (`id`, `survey_Id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_shiftdata_survey1_idx` (`survey_Id` ASC) VISIBLE,
  CONSTRAINT `fk_shiftdata_survey1`
    FOREIGN KEY (`survey_Id`)
    REFERENCES `mydb`.`survey` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`survey_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`survey_question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Survey_Id` INT NULL DEFAULT NULL,
  `Question_Id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `survey_id_fk_idx` (`Survey_Id` ASC) VISIBLE,
  INDEX `question_id_fk_idx` (`Question_Id` ASC) VISIBLE,
  CONSTRAINT `question_id_fk`
    FOREIGN KEY (`Question_Id`)
    REFERENCES `mydb`.`question` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `survey_id_fk`
    FOREIGN KEY (`Survey_Id`)
    REFERENCES `mydb`.`survey` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1004
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`surveyanswer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`surveyanswer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answer` TEXT NULL DEFAULT NULL,
  `survey_question_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_survey_question_id_idx` (`survey_question_id` ASC) VISIBLE,
  CONSTRAINT `fk_survey_question_id`
    FOREIGN KEY (`survey_question_id`)
    REFERENCES `mydb`.`survey_question` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 990
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(60) NULL DEFAULT NULL,
  `dateOfBirth` DATE NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(15) NULL DEFAULT NULL,
  `userID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_userId_idx` (`userID` ASC) VISIBLE,
  CONSTRAINT `fk_userId`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`user` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
